# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

monitor = DP-3,1920x1080@144,1280x0,1

animations {
  enabled = false
}

input {
    kb_layout = us
    kb_options = ctrl:nocaps
    follow_mouse = 1
    numlock_by_default = true

    repeat_delay = 220
    repeat_rate = 85

    scroll_points = 4

    touchpad {
        natural_scroll = yes
        disable_while_typing = true
        clickfinger_behavior = true
    }
    special_fallthrough = true

    follow_mouse = 1
    scroll_factor = 1.5
}

device {
    name = logitech-g305-1
    accel_profile = flat
    sensitivity = 1
}

decoration:blur:size = 1
decoration:blur:passes = 1
animations:enabled = 1
decoration:blur:xray = 1
decoration:blur:enabled = 0
