# You can put your preferred keybinds here
# https://wiki.hyprland.org/Configuring/Binds/

bind = Alt, Space, exec, true
bind = Alt, Return, exec, ghostty # ghostty, kitty

bind = Alt, 1, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 1 
bind = Alt, 2, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 2 
bind = Alt, 3, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 3 
bind = Alt, 4, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 4 
bind = Alt, 5, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 5 
bind = Alt, 6, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 6 
bind = Alt, 7, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 7 
bind = Alt, 8, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 8 
bind = Alt, 9, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 9 
bind = Alt, 0, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 10 

bind = Alt+Shift, 1, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 1 # [hidden]
bind = Alt+Shift, 2, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 2 # [hidden]
bind = Alt+Shift, 3, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 3 # [hidden]
bind = Alt+Shift, 4, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 4 # [hidden]
bind = Alt+Shift, 5, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 5 # [hidden]
bind = Alt+Shift, 6, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 6 # [hidden]
bind = Alt+Shift, 7, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 7 # [hidden]
bind = Alt+Shift, 8, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 8 # [hidden]
bind = Alt+Shift, 9, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 9 # [hidden]
bind = Alt+Shift, 0, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 10 # [hidden]

bind = Super, h, movefocus, l
bind = Super, l, movefocus, r
bind = Super, k, movefocus, u
bind = Super, j, movefocus, d

bind = Alt, mouse_up, workspace, +1 
bind = Alt, mouse_down, workspace, -1 

bindm = Super, mouse:272, movewindow
bindm = Super, mouse:273, resizewindow

bind = Alt, q, killactive

bind = Alt, f, togglefloating
bind = , F11, fullscreen

