alias gs='git status'
alias ga='git add'
alias gaa='git add .'
alias gc='git commit -m'
alias gca='git commit -am'
alias glf='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'
alias gp='git push'
alias gpl='git pull'
alias gb='git branch -m'
alias gco='git checkout'
alias gl='git log --oneline'
alias gd='git diff'
alias gds='git diff --staged'
alias gr='git reset'
alias grh='git reset --hard'
alias gst='git stash'
alias gsp='git stash pop'
