$scrPath = $HOME/.local/share/bin

monitor = ,preferred,auto,auto


exec-once = ags run
exec-once = $scrPath/resetxdgportal.sh
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP 
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = $scrPath/polkitkdeauth.sh 
exec-once = blueman-applet 
exec-once = udiskie --no-automount --smart-tray 
exec-once = nm-applet --indicator 
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store 
exec-once = $scrPath/batterynotify.sh 
exec = hyprshade on grayscale

# exec-once = $scrPath/swwwallpaper.sh 


env = PATH,$PATH:$scrPath
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = MOZ_ENABLE_WAYLAND,1
env = GDK_SCALE,1

input {
    kb_layout = us
    kb_options = ctrl:nocaps
    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0
    force_no_accel = 1
    numlock_by_default = true
    repeat_rate = 80
    repeat_delay = 300
}

device {
    name = elan1201:00-04f3:3098-mouse
    sensitivity = 2
}

gestures {
    workspace_swipe = true
    workspace_swipe_fingers = 3
}


dwindle {
    pseudotile = yes
    preserve_split = yes
}

master {
    new_status = master
}


general {
  # see https://wiki.hyprland.org/configuring/variables/ for more

  gaps_in = 8
  gaps_out = 8
  border_size = 0

  col.active_border = rgba(A580DAFF)
  col.inactive_border = rgba(31313600)
  layout = dwindle

  # please see https://wiki.hyprland.org/configuring/tearing/ before you turn this on
  allow_tearing = false
}

misc {
    vfr = 1
    vrr = 1
    enable_swallow = true
    # swallow_regex = (kitty)
    
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    new_window_takes_over_fullscreen = 2
    allow_session_lock_restore = true
    
    initial_workspace_tracking = false
}

animations {
  enabled = false
}

xwayland {
  force_zero_scaling = true
}

exec = gsettings set org.gnome.desktop.interface font-name 'Cantarell 10'
exec = gsettings set org.gnome.desktop.interface document-font-name 'Cantarell 10'
exec = gsettings set org.gnome.desktop.interface monospace-font-name 'CaskaydiaCove Nerd Font Mono 9'
exec = gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
exec = gsettings set org.gnome.desktop.interface font-hinting 'full'

decoration {
    rounding = 8
    dim_special = 0.3
    blur {
      enabled = false
    }
}

source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/monitors.conf
