# Main modifier
$mainMod = ALT
$scrPath = ~/.local/share/bin

# Core applications
$term_fallback = xterm -sh 1.23
$editor = neovide
$browser = firefox

# Launchers
bind = $mainMod, SPACE,    exec, pkill -x rofi || $scrPath/rofilaunch.sh application launcher

# Brightness
bind = $mainMod, PAGE_UP,  exec, brightnessctl set +10%
bind = $mainMod, PAGE_DOWN,exec, brightnessctl set 10%-

# Terminals & Apps
bind = $mainMod, Return,   exec, kitty
bind = $mainMod SHIFT, Return, exec, $term_fallback
bind = $mainMod SHIFT, b,  exec, kitty btm -b

# Utilities
bind = $mainMod SHIFT, p,       exec, $scrPath/screenshot.sh s
bind = $mainMod, grave,   exec, $scrPath/screenshot.sh s
bind = $mainMod, t,       exec, convert x: -modulate 100,0 -resize 400% -set density 300 png:- | tesseract stdin stdout | xclip -selection clipboard
bind = $mainMod SHIFT, c, exec, hyprpicker -a

# Audio & Media
bind = $mainMod, Prior,    exec, pactl set-sink-volume @DEFAULT_SINK@ +1%
bind = $mainMod, Next,     exec, pactl set-sink-volume @DEFAULT_SINK@ -1%

# bind = $mainMod, p,        exec, playerctl --player spotify play-pause # to +
bind = $mainMod, bracketright, exec, playerctl --player spotify next
bind = $mainMod, bracketleft,  exec, playerctl --player spotify previous

# Window Management
bind = SUPER, h,          movefocus, l
bind = SUPER, l,          movefocus, r
bind = SUPER, k,          movefocus, u
bind = SUPER, j,          movefocus, d
bind = SUPER SHIFT, h,    movewindow, l
bind = SUPER SHIFT, l,    movewindow, r
bind = SUPER SHIFT, k,    movewindow, u
bind = SUPER SHIFT, j,    movewindow, d
bind = $mainMod, q,       killactive
bind = $mainMod, TAB,     workspace, previous
bind = $mainMod, f,       togglefloating
bind = $mainMod, s,       pin
bind = , F11,             fullscreen

# Resize Mode
bind = $mainMod, r,       submap, resize
submap = resize
binde = , h,              moveactive, -30 0
binde = , l,              moveactive, 30 0
binde = , k,              moveactive, 0 -30
binde = , j,              moveactive, 0 30
binde = SHIFT, h,         resizeactive, -40 0
binde = SHIFT, l,         resizeactive, 40 0
binde = SHIFT, k,         resizeactive, 0 -40
binde = SHIFT, j,         resizeactive, 0 40
bind = , escape,          submap, reset
submap = reset

# Workspaces (1-10)
bind = $mainMod, 1,       workspace, 1
bind = $mainMod, 2,       workspace, 2
bind = $mainMod, 3,       workspace, 3
bind = $mainMod, 4,       workspace, 4
bind = $mainMod, 5,       workspace, 5
bind = $mainMod, 6,       workspace, 6
bind = $mainMod, 7,       workspace, 7
bind = $mainMod, 8,       workspace, 8
bind = $mainMod, 9,       workspace, 9
bind = $mainMod, 0,       workspace, 10

# Move to Workspaces (1-10)
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Mouse Bindings
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow


