# exec = export SLURP_ARGS='-d -c DEE6C6BB -b 424A3244 -s 00000000'

general {
    col.active_border = rgba(E3E3D839)
    col.inactive_border = rgba(8F928430)
}

misc {
    background_color = rgba(12140DFF)
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(12140DFF)
        col.text = rgba(E3E3D8FF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(E3E3D8), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(E3E3D8), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(E3E3D8), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrulev2 = bordercolor rgba(B7D085AA) rgba(B7D08577),pinned:1